# Generated by Django 5.2.8 on 2025-12-13 10:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texte About (EN)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_fr',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texte About (FR)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_en',
            field=models.CharField(default='About Me', max_length=100, verbose_name='Titre About (EN)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_fr',
            field=models.CharField(default='À propos', max_length=100, verbose_name='Titre About (FR)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_en',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Description Hero (EN)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_fr',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Description Hero (FR)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=models.CharField(default='Bilingual French | English', max_length=100, verbose_name='Sous-titre (EN)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_fr',
            field=models.CharField(default='Bilingue Français | Anglais', max_length=100, verbose_name='Sous-titre (FR)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(default='Web Developer & Customer Success Specialist', max_length=255, verbose_name='Titre Hero (EN)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_fr',
            field=models.CharField(default='Développeuse Web & Spécialiste Customer Success', max_length=255, verbose_name='Titre Hero (FR)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (EN)')),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Ex: 2022 ou 2020-2021', max_length=20)),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (EN)')),
                ('company', models.CharField(max_length=200)),
                ('description_fr', wagtail.fields.RichTextField(blank=True, verbose_name='Description (FR)')),
                ('description_en', wagtail.fields.RichTextField(blank=True, verbose_name='Description (EN)')),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (EN)')),
                ('description_fr', wagtail.fields.RichTextField(verbose_name='Description (FR)')),
                ('description_en', wagtail.fields.RichTextField(verbose_name='Description (EN)')),
                ('technologies', models.CharField(help_text='Séparées par des virgules (ex: Python, Django, Wagtail)', max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('webdev', 'Développement Web'), ('customer', 'Customer Success'), ('digital', 'Marketing Digital'), ('tools', 'Outils & CRM')], max_length=50)),
                ('level', models.IntegerField(default=50, help_text='Niveau de compétence (0-100)')),
                ('order', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'name'],
            },
        ),
    ]
